### ISSUE TITLE
Does not work with Resque 1.25

### ISSUE THREAD

**Issue by aselder** [wr0ngway/resque-concurrent-restriction#6]
It looks like Resque 1.25 removed Resque.constantize

    *** Error reserving job: #<NoMethodError: undefined method `constantize' for Resque Client connected to redis://x.x.xx.x:6379/0:Module>
    *** /var/apps/xxx/shared/bundle/ruby/1.8/gems/resque-concurrent-restriction-0.5.9/lib/resque/plugins/concurrent_restriction/concurrent_restriction_job.rb:133:in `tracking_class'
    /var/apps/xxx/shared/bundle/ruby/1.8/gems/resque-concurrent-restriction-0.5.9/lib/resque/plugins/concurrent_restriction/concurrent_restriction_job.rb:422:in `next_runnable_job'
